### ISSUE TITLE
lunr fails to find matches in entire words.

### ISSUE THREAD

**Issue by MathieuDuponchelle** [olivernn/lunr.js#137]
Not sure how to best phrase this, here is an example : 

```
  var index = new lunr.Index();

  index.ref('id');
  index.field('title', { boost: 10 });
  index.add({                                                                                                          
        id: "ges.timelineelement",                                                                                     
        title: "TimelineElement",                                                                                      
      });                                                                                                              
  var results = index.search("TimelineElem");                                                                          
  console.log ("results length : " + results.length);                                                                  
  var results = index.search("Element");                                                                               
  console.log ("results length : " + results.length);
```

this prints:

```
results length : 1
results length : 0
```

I may be missing something obvious here, but I would expect the index to match Element with TimelineElement with a low-ish score, what's going wrong here ?

**Comment by weixsong** [comment]
actually the function you want is not supported by lunr.js, lunr.js could not search by middle part of one entire token.
I think even google don't do this.

**Comment by olivernn** [comment]
@weixsong is right, this isn't currently available in lunr. The search is always a prefix search, so in your example a search for `TimelineElem` works because lunr is putting in wildcards at the end, e.g. `TimelineElem` becomes `^TimelineElem*`. When searching for `Element` lunr is basically doing a search for `^Element*` which does not match the documents you have.

It looks like, from your example, that you want lunr to be able to understand snake cased tokens as seperate tokens, e.g. `TimelineElement` is actually made of two tokens, `timeline` and `element`. You can add a custom tokeniser to the pipeline to split snake cased words like this into seperate tokens and then your search for `Element` will work.

**Comment by MathieuDuponchelle** [comment]
Yeah that's what I ended up doing, thanks

On Thu, Apr 9, 2015 at 9:26 PM, Oliver Nightingale <notifications@github.com

**Comment by MathieuDuponchelle** [comment]
@weixsong by the way of course google do this :)
