### ISSUE TITLE
Issue when minifying and concat with other libraries

### ISSUE THREAD

**Issue by darkmavis1980** [olivernn/lunr.js#162]
Hi, I'm not sure why, but I don't see any semicolon in the lunr.js code. While the code works as its own, it brings big issues when you have to minify and concact the code with other libraries via GruntJS.
It simply stop anything that gets loaded after lunr.js to work.
Again, not sure why it has been decided to remove semicolons, but it would be a good idea to put it back.
Also jshint will fail because of that.

**Comment by olivernn** [comment]
What build of lunr are you seeing the issues on? Are you using the pre-built versions found in this repository? What, specifically, are the problems you are seeing when combining lunr with other libraries via Grunt? What are the other libraries?

Is it possible for you to provide a means of reproducing the issue you are seeing?

**Comment by darkmavis1980** [comment]
Essentially I'm working on a quite big AngularJS project, and what we do when we deploy the code is to minify all the js and css into a few compressed and minified js files, where for example in the vendor.js we have all the libraries we use, like angular itself, other stuff, and lunr.js.
Essentially any library that is added after lunr.js in this big minified file will break, essentially because there are no semicolons to tell to JS where lunr.js ends and where the next library starts.
There's any valid reason why all the semicolons have been omitted by the code?
I'm using the latest build of lunr.js

**Comment by olivernn** [comment]
Sorry for the delay in my response, work has been busy!

Are you using the [minified build](https://github.com/olivernn/lunr.js/blob/master/lunr.min.js) of lunr or the [non-minified build](https://github.com/olivernn/lunr.js/blob/master/lunr.js)?

There has been an [issue](https://github.com/olivernn/lunr.js/issues/61) with this in the past which I thought was fixed, though it sounds like you have found a regression. Just trying to understand where the issue is so I can fix it.

I'm not really interested in a debate over whether semi-colons should or should not be in the source files, just know that in this project the sources _do not_ contain semi-colons and they are supposed to be added as part of the [build](https://github.com/olivernn/lunr.js/blob/master/Makefile#L31-L35), if this is not happening then its a bug that I'd like to fix!

Taking a look at the build makes me think that a [change that introduced the AMD wrapper](https://github.com/olivernn/lunr.js/issues/72) may have caused this issue, but I need a bit more info from you to try and pinpoint and fix the issue.

**Comment by darkmavis1980** [comment]
I'm using the non-minified build as that's the default that bower inject in my project, as the minification happens later where a grunt task minify all the vendor files

**Comment by olivernn** [comment]
Would you mind testing this [build](https://gist.github.com/olivernn/37d44fe201e617b74b6b)?

If it works for you I'll commit and push the changes to the build, just want to check that the changes solve you're problem.

**Comment by darkmavis1980** [comment]
Just tested, seems to work fine now :-)

**Comment by olivernn** [comment]
I've just pushed version [0.5.11](https://github.com/olivernn/lunr.js/releases/tag/v0.5.11) which includes a fix to the build system to produce the file I shared with you in the gist. Let me know if you have any other issues.
