### ISSUE TITLE
Nested field support for index setup

### ISSUE THREAD

**Issue by lnwdr** [olivernn/lunr.js#164]
When I have documents with a structure like:

```JSON
{
  name: "Some name",
  address: {
    street: "Main Street",
    number: "42",
    city: "Some Town"
  }
}
```

I'd like to search among the `city` field but I can only specify fields on the top level of the document when setting up my index:

```JS
var index = lunr(function () {
    this.field('address')
});
```

It would be nice, if I could specify a nested field for indexing. Something like this:

```JS
var index = lunr(function () {
    this.field('address.city');
    //or maybe:
    this.field(['address', 'city']);
});
```

**Comment by olivernn** [comment]
This is a [request](https://github.com/olivernn/lunr.js/issues/100) that comes up quite a [lot](https://github.com/olivernn/lunr.js/issues/23).

The reason I haven't implemented this change is that I think it can (and should) be done outside of lunr, since the structure of the document is very specific to each user.

In your use case you would just need to have a conversion function that maps your document to something that can be indexed:

```javascript
var mapper = function (document) {
  return {
    name: document.name,
    city: document.address.city,
    street: document.address.street
  }
}

var idx = lunr(function () {
  this.field('name')
  this.field('city')
  this.field('street')
})

idx.add(mapper(document))
```

This also gives you the flexibility to combine certain fields into a single field to be indexed by lunr or doing any other conversion you want before lunr starts to index the fields.

**Comment by lnwdr** [comment]
The problem with this is that it changes the document's structure which can be important for the rest of the application. For example when I iterate on the document's fields somewhere, that part needs to be aware of this mapping, leading to my indexing logic spread all over the application.

**Comment by olivernn** [comment]
I'm not suggesting changing the way you represent your data throughout your entire application, just for when you add it to the lunr index. Or am I missing something?

**Comment by Petesta** [comment]
@olivernn I'm not sure if @selfawaresoup is referring to the fact that, you can provide a mapper function from the document that needs to be transformed in order for lunr to index properly. But then what do you with the original mapping of the document because `lunr_instance.search(SEARCH_TERM)` will return the documents after they've transformed by the mapper function. Are we to provide another transformation to get the original document structure or additional filtering on the original documents after `lunr_instance.search(SEARCH_TERM)` has run?

I'm not sure if this is what they were saying.

**Comment by olivernn** [comment]
@Petesta the search method does not return the documents that match, instead it returns a reference, i.e. the id of the document. The results are covered in more detail in the [search results docs](https://lunrjs.com/guides/core_concepts.html#search-results), they look like this:

```javascript
[{
  "ref": "123",
  "score": 0.123456,
  "metadata": {...}
}]
```
