### ISSUE TITLE
Store to levelDB or any other db system

### ISSUE THREAD

**Issue by fmmsilva** [olivernn/lunr.js#189]
Is it possible?

**Comment by olivernn** [comment]
It depends :wink: 

The index supports being serialized to JSON:

```javascript
JSON.stringify(idx)
```

This dumps the _entire_ index as JSON, this is how static site generators provide a pre-build index etc. Beyond that though there is not any support to store aspects of the index in a db system. What exactly is your use case?

Many years ago, the very [first versions](https://github.com/olivernn/lunr.js/tree/0a8e7272ad951b5002733976c29a2e6c45f43ff4) of lunr were built on top of [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). The problem was that it was _very_ slow, and hence I changed everything to be in memory.

**Comment by fmmsilva** [comment]
I would like to store it in a DB that has concurrency support, etc.

**Comment by missinglink** [comment]
just curious as to your use case @fmmsilva? if you want a more traditional database/backend/server architecture you could use elasticsearch or solr?

**Comment by fmmsilva** [comment]
Yes.. that's what I am doing right now... I was justing looking for some lightweight and simple alternative while I don't finish all the solr installation/configuration/client etc...

**Comment by olivernn** [comment]
Really, lunr is best suited to be run in-process, typically (though not necessarily) in a browser. You could certainly wrap the library in a server using node, but, unless setting up elastic search (or solr) is _very_ complicated and time-consuming, you're better of using those if you need concurrency or more fine grained persistence etc.

I guess an apt analogy would be the difference between SQLite and MySQL, except lunr is not a drop in replacement for either elasticsearch or solr (nor is it as awesome as SQLite).
