### ISSUE TITLE
Substring matching?

### ISSUE THREAD

**Issue by bomberstudios** [olivernn/lunr.js#193]
Hi there,

I'm loving Lunr, and how easy it is to implement it and use it on a GitHub Pages site.

I have a question (sorry if this has been already replied, searched the issue database and didn't find anything relevant): is it possible for Lunr to do substring matching? i.e: I have a page called "MSArtboardGroup", and I want it to show up as a result when searching for "Artboard".

Can Lunr do this, or is there a plugin that lets it do it?

Thanks in advance! : )

**Comment by olivernn** [comment]
Lunr does do substring matching, but only with the end of a string, e.g. a search for "Artboard" would match "ArtboardGroup" but not "MSArtboardGroup". That is to say that every search implicitly has a wildcard at the end of the string, e.g. "Artboard*", it is not possible to have a wildcard anywhere else in the search string currently.

There is however a workaround that might help in this particular situation. I'm going to take a wild guess and assume that "MSArtboardGroup" is actually an Objective C class name, where "MS" is the prefix or namespace.

You could add a [pipeline function](http://lunrjs.com/docs/#Pipeline) that would detect that the token is actually an prefixed class name and return the class name without the prefix.

```javascript
var stripObjCNameSpace = function (token) {
  if (token.slice(0, 2) === "ms") {
    return token.slice(2)
  } else {
    return token
  }
}

// only strictly necessary if you are serialising the index
lunr.Pipeline.registerFunction(stripObjCNameSpace, 'stripObjCNameSpacce')

// insert your pipeline function right before stemming
idx.pipeline.before(lunr.stemmer, stripObjCNameSpace)
```

Hopefully this makes sense, all tokens before indexing or searching are passed through the pipeline, and here we just trim the first two characters if they are "ms" (or whatever your prefix is). This means that if people search for "MSArtboardGroup" the index will actually be searched for "ArtboardGroup" which is what will have been indexed.

This is not a _great_ solution. If you try and trim a prefix that is more common in english then you're going to get some weird results. In that case the simplest thing would be to prepare your search documents with some list of tags already with alternative names to match against, e.g.

```javascript
{
  "title": "MSArtboardGroup",
  "body": "A group of artboards",
  "url": "http://blah",
  "id": 1,
  "tags": ["ArtboardGroup", "anything", "else"]
}
```

You would then just add "tags" as an extra field to index.

```javascript
  var idx = lunr(function () {
    this.field('title', { boost: 100 })
    this.field('tags', { boost: 10 })
    this.field('body')
  })
```

**Comment by MathieuDuponchelle** [comment]
+1 , this is the problem I had mentioned in https://github.com/olivernn/lunr.js/issues/137 , it seems like a pretty basic feature to have, and something a DAWG could handle (http://stevehanov.ca/blog/index.php?id=115), what's your reasoning for using a trie over a dawg btw ?

**Comment by olivernn** [comment]
@MathieuDuponchelle yes this is the same problem as in #137.

Replacing the existing trie with a finite state machine is something I am keen to implement in lunr. It is, however, not quite as simple as just swapping out the trie implementation for an FST implementation.

There are operations that are not possible with an FST that _are_ possible with a trie, some of these were important enough to my use case when I first wrote lunr that I chose to use a trie. Over time, the use cases for lunr have changed and now the arguments for using a trie are less compelling, hence why I'm keen to move towards using an FST in the next major version of lunr.

**Comment by bomberstudios** [comment]
Just realized I never said thanks for the detailed info. I think I'll be able to use it to build a workaround on my system. 

Much appreciated, keep up the great work!

**Comment by MathieuDuponchelle** [comment]
Hey, ended up rolling my own, wanted to share my approach here cause I think it's fairly original and has significant advantages over lunr for my specific use case, here's an example result:

https://people.collabora.com/~meh/glib_hotdoc/html/index.html

The constraints I wanted to respect were:

* search has to work locally or with pages hosted on a simple http server
* enabling search over multiple pages (in that example there are 274 html pages)
* minimal amount of computation needed on the client side.
* minimal size for the initial download (in that example the initial download is 392 kilobytes)
* Full text search with fuzzy-matching, completions and substring matching

My approach is to generate a trie and encode it with four bytes per node, and have the client download only this at first, the generation is done in python.

I've got some javascript code that implements fuzzy matching, substring matching etc, when a match is found, a file with the name of the match is retrieved, for example if the user searched for foo, and a match was found for "the_foo_bar", then a file named "remote_url/search_folder/the_foo_bar" is retrieved.

This file references the various urls where the match is mentioned, in a second stage I also query "fragments", for example if "the_foo_bar" is mentioned in "the_foo_bar.html#doing_ze_foo", a fragment is queried at "remote_url/search_folder/fragments_folder/the_foo_bar.html#doing_ze_foo.fragment".

This fragment contains the html that could be seen if the user navigated to that page and anchor.

I also implemented a small ellipsizing function that is a bit smarter than existing ellipsizers I could find, in that it can put ellipsis *inside* search results (search for "testtreemodel" for an example of this), but that's not really related.

Let me know what you think, I haven't yet finalized the implementation, but I'm already pretty confident in this approach.

**Comment by MathieuDuponchelle** [comment]
ping ?

**Comment by olivernn** [comment]
@MathieuDuponchelle I took a look at your implementation, looks pretty good, I'll have to take a closer look through the code and see if there is anything I can ~~steal~~ borrow ;)

I'm looking at using a FSM for the reverse index, and then treating queries against this also as FSMs and basically doing an intersect of the two. This should allow for basic string searches, fuzzy matching or edit distance matches as well as more advanced queries that can be some subset of a regular expression etc. Implementation is very early days but is promising so far. I took a bit of inspiration from this [article](http://blog.burntsushi.net/transducers/), well worth a read.

**Comment by MathieuDuponchelle** [comment]
+1 for FSM, I got stuck when using a DAWG and trying to encode it "succinctly", at that point I read about "minimal acyclic finite state transducers" which seemed to be the thing I wanted, and decided there were too many words I didn't know in that name, and the encoded trie was light enough for my needs.

The data structure itself is thus really not the interesting part in my implementation, as it's simply a trie with some levenhstein peppered on it :)

> I'll have to take a closer look through the code and see if there is anything I can steal borrow

By all means do! I'm really not into javascript anyway (which might be visible when looking at my code), and maintaining a client-side search library wasn't part of my plans when I started my current project :)

I'm sorry about not trying to implement this directly in lunr.js and getting it merged, but it seemed to me like there were too many differences and that I would just be working against the design. Note that lunr does have things that I'd love to have too, such as the stemmer, and it would be pretty awesome if you could implement my ideas and still keep these features.

To summarize the things I would consider necessary to drop my code entirely and use lunr instead:

* Separate the data structure responsible for looking up tokens from the urls that reference them.
* Provide a way to access the "fragments" from the urls
* Allow building the index "server-side", it's at this stage that the "token to urls" and "url to fragment" maps should be created (these maps actually being large sets of files)
* Make the build fast enough (my current implementation is python, it takes 5 seconds for the glib documentation and that's already too much for my taste, ideally it could be a C implementation + wrappers for python). Note that my current implementation allows for updating an encoded trie when not all html files have changed, but there is a fixed cost to decoding and reencoding it which I'm not sure how to best get rid of.
* On the lookup, client-side side of things, I need the feature to work locally without a http server. This means that to work cross-browser as well, I could not use XHR, as it's disabled on chrome for the file:// protocol. In order to work around that, I have to retrieve the urls and fragments by wrapping them in javascript, injecting scripts in <head>, and implementing callbacks in the client code. The same technique is used to retrieve the trie itself when on the file:// protocol, I however use a XHR for retrieving it when not run locally, as making it a javascript file requires encoding it in base64, and that makes the file a bit larger.
* Ideally, lunr could provide an optional javascript file providing a default, hookable view and controller, wrapping a typeahead library such as twitter-typeahead, that's a pretty separate concern though.

I realize this is a fair amount of work, but:

* I've worked through most of the headaches
* It would open up a large range of new use-cases for lunr
* I'd rather not be the upstream for too many projects :)

**Comment by MathieuDuponchelle** [comment]
Shameless plug by the way, I humbly think the API reference for lunr is a bit crappy (http://lunrjs.com/docs/) , my documentation tool can not parse javascript yet, but if someone *wink* implemented an extension for this, then you could have a much better looking documentation :)

**Comment by olivernn** [comment]
Oh yeah, the docs are neglected, which is a shame. Will definitely take a look at your doc tool, thanks!

**Comment by MathieuDuponchelle** [comment]
So @olivernn , did you find some time to try and see how my approach could fit lunr? I haven't done much in my search code since then, which means lunr still has features I'd very much like to have ^^

**Comment by MathieuDuponchelle** [comment]
@duhaime which link? :) The source code for the search implementation isn't standalone, but is part of a larger project: <https://github.com/hotdoc/hotdoc/blob/master/hotdoc/extensions/search/create_index.py> is the entry point for the generation code, and https://github.com/hotdoc/hotdoc_bootstrap_theme/blob/master/src/js/search.js for the client-side. Note that I have started a rewrite of the generation code in C as the python version is a bit slow when you're indexing thousands of files :)

**Comment by duhaime** [comment]
Ah, awesome, thanks! I may well create a standalone project to support searches over a disk-persisted trie to keep things simple. I don't think it will be too much work, but I haven't started to sink my teeth in yet.

Regardless, your example will be a big help--thanks again for following up!

**Comment by MathieuDuponchelle** [comment]
cool, keep me updated :)
