### ISSUE TITLE
Won't work with some words

### ISSUE THREAD

**Issue by pgn-vole** [olivernn/lunr.js#201]
It seems that some words cannot get matched.

Here is how to reproduce:

```javascript
 
 var index = lunr(function () {
    this.field('title', {boost: 10})
    this.ref('id')
  })

index.add({
    id: 1,
    title: 'Just What'
  })

index.search('Just') // []  
```

By replacing "Just" with an other word it seems to work fine.

**Comment by olivernn** [comment]
Both of those words are considered [stop words](https://github.com/olivernn/lunr.js/blob/master/lib/stop_word_filter.js) by lunr and are filtered out. This means they don't appear in the index and are stripped from searches.

Stop words are removed because they are _very_ common and usually contribute little to differentiating one document from another, this helps keep the index size down and improves query performance.

If you _really_ need to search for words that are stop words you can remove the stop word filter like so:

```javascript
index.pipeline.remove(lunr.stopWordFilter)
```

Alternatively you can generate your own stop word filter that is more specific to your use case:

```javascript
var myStopWordFilter = lunr.generateStopWordFilter(['your', 'stop', 'words', 'here'])
index.pipelline.before(lunr.stopWordFilter, myStopWordFilter)
index.pipeline.remove(lunr.stopWordFilter)
```
