### ISSUE TITLE
Matcher for auto complete

### ISSUE THREAD

**Issue by markvital** [olivernn/lunr.js#211]
I'm looking for simple search enigine, with metadata support. It would be great to have a matcher in Lunr.js, so it can be integrated with auto complete, like typeahead.js. Something like this:
```
idx.match("lo")
..
idx.match("lov")
..
idx.search("love")
```

**Comment by markvital** [comment]
The match should return text suggestions, just like in autosuggest in Google search.
Here are some examples in other search engine's libraries:
https://qbox.io/blog/quick-and-dirty-autocomplete-with-elasticsearch-completion-suggest
https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md

It is different from search, because there might be several tokens for one document returned, where is in search you only get one document per query.

For example I have some documents in the index:
```
{
    "title": "Product1",
    "description": "Product1 Description",
    "tags": [
        "blog",
        "magazine",
        "responsive design",
        "responsive layout",
        "responsiveness"
    ]
}

{
    "title": "Product2",
    "description": "Product2 Description",
    "tags": [
        "blog",
        "paypal",
        "responsive",
        "skrill",
        "wordland"
    ]
}
```

Search for the querry "responsive" will return:

```
[
   {"title" : "Product1", ...}, 
   {"title" : "Product2", ...}
]
```

Whereas suggest for the "responsive" will return:
```
[
  {"text": responsive", "title" : "Product2", ...}, 
  {"text": responsive design", "title" : "Product1", ...}, 
  {"text": responsive layout", "title" : "Product1", ...},
  {"text": responsiveness", "title" : "Product1", ...}
]
```

**Comment by missinglink** [comment]
hey @olivernn I have been lurking for some time and I've seen a few of these autocomplete requests come through. If you're interested in having a discussion, I'd be happy to help out. I have a fairly extensive knowledge of the design patterns and analysis techniques required to do this from my work on https://github.com/pelias/pelias.

**Comment by olivernn** [comment]
So, to some extent, this is possible right now. An index has a `tokenStore`, this is a trie of all the tokens that are in the index. It has a method, `expand` that will find all words with a given prefix, e.g.

```javascript
idx.tokenStore.expand("foo") // returns an array of all known tokens with "foo" as a prefix
```

That said, there are some caveats. Specifically, the tokens in the `tokenStore` are the result of running the original tokens through the indexes pipeline. With a default pipeline this will mean that the tokens are stemmed, missing stop words and trimmed of what lunr thinks are redundant characters. You can see the result of this in the [example](http://lunrjs.com/example/). Open up the console and try the following:

```javascript
idx.tokenStore.expand("check")
```

The data in the example index isn't the cleanest, but you can see the impact that stemming has on the tokens.

Alternatively you could create an index specifically for autocomplete, perhaps something like the following:

```javascript
var autoCompleteIdx = lunr(function () {
  this.field('text')
})
```

With the documents structured like this:

```javascript
{
  id: "word",
  text: "word",
}
```

Having the document ID also be the word means that the results of the search will contain the original word you inserted, but the lookup will make use of any stemming, so e.g. in this example a lookup for "words" would suggest the document with ref "word"

```javascript
autoCompleteIdx.search("words") 
[{
  ref: "word",
  score: 0.123456789
}]
```

I think the key difficulty lunr has with this is that it doesn't really store the words in a document, it converts the document to a form that is easy to index and search, without any regard for actually getting the same words out again.

@missinglink I'd be interested in hearing some ideas that you have. I'm actually fairly far along now with some changes to the implementation of lunr, so hold off on making large changes to the current implementation. I'm hoping to get something out for people to preview in the next couple of weeks though.

**Comment by missinglink** [comment]
Oh actually, I just had another quick look through the code and I agree, using a trie will give fast lookup performance, so for general-use, what you have already is going to work great!

Users will just have to understand the impact the analysis pipeline will have on their tokens.

I think maybe that my point-of-view is skewed towards having a high performance autocomplete of 200MM+ records, and the same performance considerations don't really apply in the browser :)

There's a super efficient way of doing the intersection using sparse bitmasks I could show you, it's significantly faster than sorted-set intersection at 10MM+ record scale (sub 1ms intersections) but that's also probably not a design goal of lunr?

The current implementation doesn't quite work 'out-of-the-box', as you pointed out the `tokenStore.expand()` function uses the trie to find common prefixes:

```javascript
idx.tokenStore.expand("check")
["check", "checkbox", "checkbox'", "checked="yes"&gt;&lt;/input&gt", "checked="yes"&gt;&lt;/input&gt;&lt;/span&gt", "checked="check", "checkvalu", "checkimag"]
```
```javascript
idx.tokenStore.expand("why")
["why?</p", "why?i"]
```
```javascript
idx.tokenStore.expand("the")
["ther", "there'", "therebi", "them...so"]
```

with the last two examples the original token is omitted, I assume this is to do with stop words and synonyms, both of which are a pain for autocomplete, as are traditional stemmers.

For the document `Why does my checkbox return the wrong state?` would lunr currently match for the input `why do` ?

I'm actually starting to doubt the ease at which a 'general purpose' autocomplete engine would be to create, for example indexing "A & B" and querying "a an" is difficult because of the synonym expansion.

The main issue will be 'jitter', like when you start typing a phrase and it find it, then as you type more it disappears and then comes back as you finish the word.

Anyway, sorry for the brain-dump, the tl;dr it's complicated and would require a rethink of some of the analysis, maybe we can have a call or move this to another issue to discuss in more detail?

**Comment by markvital** [comment]
anyway, would love to have this implemented anytime soon

**Comment by olivernn** [comment]
@missinglink thanks for the comment, some interesting things to think about. If you have a link or similar on the technique you mentioned using sparse bit masks I'd be really interested to read up on it. While having 200MM records in a browser is probably pushing what is a sensible use case for lunr, I'm sure there are things I could learn anyway!

You're right in that actually getting a performant and accurate auto-complete engine is a task in itself. You can certainly get pretty far by bending lunr in the ways mentioned, and for a lot of people it will cover the 90% of cases, but there is certainly scope for something more focused on the task at hand.

The two cases that you mention, where the original token is missing in the output, is because they are stop words. Removing the stop word filter would solve this particular issue, alternatively you could just use the [`lunr.TokenStore`](https://github.com/olivernn/lunr.js/blob/master/lib/token_store.js) object directly, without ever creating an index.

@markvital between my previous answer and the detailed comments from @missinglink there should be enough for you to put together your own implementation to solve your problem. If you do get something working, either with lunr or some other implementation, please do update this issue so others might benefit.
