### ISSUE TITLE
The character 'e' does not work after the fourth character

### ISSUE THREAD

**Issue by ZeroFries** [olivernn/lunr.js#236]
If you add the letter "e" after any search that is over four characters long, it does not narrow the search further at all.

EG:
List includes "Wendy"
Search Wende and Wendy will show up, search Wene and it won't.

**Comment by olivernn** [comment]
I think you are coming up against both the stemmer and the automatic wild card search in lunr. I can assure you there is no specific code that checks whether a search is over four characters long and ends with an 'e'!

So, you documents contain the term `wendy`, this is how lunr stems `wendy`:

```javascript
lunr.stemmer("wendy") => "wendi"
```

Before performing a search lunr will stem all the search terms, because of this a search for `wendy` will obviously match the document that contains that term. What about `wende`? This is stemmed to `wend`,  but lunr also tries to be clever and inserts a wildcard at the end of the term, so you're _really_ searching for `wend*` which matches `wendi`

Now lets take a look at `wene`; lunr stems this and adds the wildcard, so the actual search term is `wene*`. This does _not_ match `wendi` and so lunr doesn't return your document.

But, actually, without wildcards and stemming, it still _shouldn't_ be a match right? `wendy` and `wene` don't match at all?

**Comment by ZeroFries** [comment]
Hahah yeah, I was wondering how this bug could surface without explicitly coding for it :P

I'm confused why Wende turns into Wend*, but Wene turns into Wene*. Why is the behavior so different? Does it have anything to do with being over 4 characters? 

The reason this bug surfaced is because one of our clients had one employee named Leanne and one named Leanna, and when searching Leanne, both employees shifts showed up and they ended up overpaying her. At least for our use case, this is very undesirable, so if this is expected behavior of the library we'll have to switch.

Thanks for getting back to me!

**Comment by olivernn** [comment]
Yikes! That sucks for your client, though not so much for Leanne (or was it Leanna?!).

There are two types of stemmer, dictionary stemming and algorithmic stemming. In a dictionary stemmer there is a large dictionary which contains every word and all its variants. These stemmer just  need to perform a find and replace using this lookup. An algorithmic stemmer instead looks for patterns in words and uses these patterns to shorten the words. For a language like English, which is very irregular, the [rules](http://snowball.tartarus.org/algorithms/english/stemmer.html) are lengthy and complex, and it doesn't _always_ get it correct.

For a library like lunr, using a dictionary stemmer would make the library prohibitively large and basically unusable in the browser, so it uses a algorithmic stemmer (porter stemmer) for English.  stemmer reduces the size of the index, and to increase recall, e.g. a search for `walking` will also match documents containing `walk` and `walked`.

If the stemmer is causing you problems it is possible to disable it:

```javascript
var idx = lunr(function () {
  // normal index definition goes here
  this.pipeline.remove(lunr.stemmer)
})
```

Let me know if that fixes your issue.

**Comment by ZeroFries** [comment]
It does! Thanks very much for your help.
