### ISSUE TITLE
support Arabic and Persian

### ISSUE THREAD

**Issue by vahidreza** [olivernn/lunr.js#247]
Do you have any plan to add Arabic and/or Persian languages to lunr.js?

**Comment by olivernn** [comment]
Me personally, no. I'm not an Arabic, nor Persian speaker/reader/writer, so you really don't want me doing something like this!

There is a [lunr-languages](https://github.com/MihaiValentin/lunr-languages) repository that does contain extensions for different languages, no Arabic, but it should give you an idea on how to add support for a language other than English.

The absolute minimum that you would need to build to get Arabic support would be something that knows how to split a string into discrete words ready for indexing. Adding a stop word filter, and stemming will produce even better results, but are not 100% required.

If you do come up with something, consider contributing to the lunr-languages project, so that others can also benefit from your work.
