### ISSUE TITLE
Is it possible to use a custom store instead of the built in in-memory one?

### ISSUE THREAD

**Issue by sacheendra** [olivernn/lunr.js#248]
Is it possible to use a custom [Store](http://lunrjs.com/docs/#Store) to store values to IndexedDB for persistent storage? 

I'm asking this because I need to store 100s of megabytes of data and don't want to serialize and deserialize for storing it in IndexedDB every time the app loads. 

Thank You!

**Comment by olivernn** [comment]
There is no built in support for swapping out the store with a custom implementation, but it should still be possible. So long as you implement the same interface the rest of the library will be none the wiser, just replace `lunr.Store` with you're own implementation.

Interestingly, way back when (nearly 6 years ago), a very early version of lunr did use [IndexedDB for storage](https://github.com/olivernn/lunr.js/commit/2a6c5eb7f495f481ee3303390325fa913a350561#diff-c98a7bedf9963a99f5c08b3257a21250). If I remember correctly I ditched it because it was very slow. It'd be interesting to see how things have moved on since then, if you put something together for this please do let me know how it turns out.

**Comment by hoogw** [comment]
@olivernn good point, localstorage and indexed db is too slow compare to in memory. The reason to use lunr is fast.
