### ISSUE TITLE
Field as array of tags – multi-word searches don't return results

### ISSUE THREAD

**Issue by chrisfay** [olivernn/lunr.js#249]
Hi,

I have a field called 'tags' and the value of field is always an array of tags. The tag format allows for multiple words, so for example indexing might look like:

```
var content = {
  id: id,      
  tags: ['foo bar', 'foo', 'bar']
};

fooIndex.add(content);
```

Given this example, I'm able to search and return results for tags provided I search for either the string 'foo' or 'bar', but 'foo bar' returns an empty search. How should I go about supporting multi-word searches in this case? It works fine when I simply index a multi-word string on a field, just not as an array like above.

**Comment by olivernn** [comment]
In the example you posted, you _should_ be able to search for 'foo bar' because there are individual tags 'foo' and 'bar', but I think I understand what you mean, a better example would be this document:

```javascript
{
  id: 1,
  tags: ['foo bar', 'baz', 'qux']
}
```

Here you should be able to search for 'foo' and get results, but searching for 'foo bar' will not give any results.

This is because, when a document's field is an array, lunr assumes that each element of the array is a token, and therefore [performs no tokenisation](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L18) (e.g. splitting on spaces).

This means that the token being indexed is literally 'foo bar'. This is fine, except, when doing a search for 'foo bar' lunr _does_ do tokenisation, and so is looking for documents with 'foo' and 'bar', not 'foo bar'.

You could ensure that each element in the document array is a single token, as in, can be searched for individually. Typically this means the tags should _not_ contain any characters that lunr will [split](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L30) on.

When searching, the search term is also tokenised in the same way as a document field. This means you _can_ pass your search as an array, which will bypass any tokenisation, e.g.:

```javascript
idx.search(['foo bar'])
```

This _might_ work now, but it isn't guaranteed to always work, so I wouldn't recommend it as a long term solution.

**Comment by chrisfay** [comment]
Hey Oliver,

Thanks for the reply. Is there a way to disable the tokenizer when indexing
an array of tags in this manner? If I submit the search as an array
globally it does resolve explicit tag matches as you mentioned (e.g. 'foo
bar'), but then I lose fuzzy matching on other fields in the index 'foo baz
bar'.

Thanks,
Chris

--
Chris Fay

**Comment by olivernn** [comment]
It's not clear to me what you are trying to achieve. Is the tag 'foo bar' really a single tag, or is it two separate tags?

If it is a single tag, then what you are asking for is effectively a leading wild card, e.g. really you want to be searching for '*bar' and this isn't currently supported. Otherwise, if it is actually two separate tags then they need to appear as two separate elements in the array.

I don't know what you mean when you say "disable the tokeniser when indexing an array of tags".

You can do anything you want to the documents _before_ they enter the index, so you could make the tag list something that responds to [`toString`](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L20) to generate what you need.

**Comment by chrisfay** [comment]
Sorry if I'm not being clear.

Is the tag 'foo bar' really a single tag, or is it two separate tags?


'foo bar' is one tag and when added to the index, users should ideally be
able to match the document by the given search examples:

   - foo bar
   - foo
   - bar

If that's not possible, at least matching on 'foo bar' should work, which
is why I asked if I could alter the tokenization when indexing these tags
so that 'foo bar' would be stored as a single token, rather than splitting
on the space to 'foo' and 'bar' separately (the result of which is that the
search 'foo bar' fails).

Does this make more sense?

--
Chris Fay

**Comment by olivernn** [comment]
That makes sense, but there are two problems:

1. As far as Lunr is concerned, a tag should be one single, indivisible, token. So you can't search by half of a tag. Lunr does insert trailing wildcards to the search so this sort of works, but not in the way you want it to
2. Lunr is getting confused because the tag contains a character it considers a token separator, when searching Lunr will convert 'foo bar' into two separate tokens, and only find documents that have both. As mentioned earlier you can take advantage of the tokeniser supporting arrays to search for "foo bar" as one token, but this is undocumented behaviour that might not always be true in future versions of Lunr.

Where does that leave you, well, I'd suggest trying to avoid using [characters](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L30) that Lunr considered as separators within tags. Sorry that's not very useful, but I'm not sure there is any other workaround with the current implementation.

I'll close this issue now as I don't think there is any fix needed/possible here, feel free to re-open or add any other workaround you come up with.
