### ISSUE TITLE
Search phrases with hyphens (-) return no results

### ISSUE THREAD

**Issue by WesCossick** [olivernn/lunr.js#255]
If a search phrase contains a hyphen (-), then no results are returned back. This can be seen in your [example](https://olivernn.github.io/moonwalkers/) when searching for the term "Rover-2".

**Comment by olivernn** [comment]
Thanks for reporting this.

I've taken a look and the problem is due to a mismatch between what the query parser and tokenizer consider a word separator.

It looks like [I thought of this](https://github.com/olivernn/lunr.js/blob/master/lib/query_lexer.js#L145-L148), but never came back to it :man_facepalming: 

The simplest fix is to use the same set of [separators](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L57-L64) as used by the tokenizer.

I think the right thing to do is to make it configurable, just like with the tokenizer. I'll have a think about the best way to achieve this.

**Comment by olivernn** [comment]
I've just pushed version 2.0.2 that contains a [fix](https://github.com/olivernn/lunr.js/commit/356d25a98c5d67548c9c65799e151cc5b6e524d3) for this.

There might be better ways of doing this that offer more customisation or more control in the future, but for now it should be fine.
