### ISSUE TITLE
Exact Matching

### ISSUE THREAD

**Issue by chriskarkowsky** [olivernn/lunr.js#266]
Hello,

I am prebuilding my index during a Metalsmith and have a "categories" and "tags" field which I am populating with a long string full of hyphenated terms, like this one:

tags: 'animation callout dynamic-bars ',
categories: 'tutorials ' 

When I go to load the index and run the search, I want to target, say for instance the 'tag' field, to search the exact tag.  So I do something like:

        var idx = lunr.Index.load(lunr_blog);
        var the_results = [];
        var lunr_search_results = idx.search("tags:dynamic-bars);
        async.forEachOf(lunr_search_results, (result,key, callback)=>{
            the_results.push({
                lunr:result, 
                ...
                })
            callback()
        }, ()=>{
            the_results.forEach((result)=>{
                console.log(result.lunr.matchData);
            })
            resolve(the_results);
        });

Here is the result from the log:

{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { dynam: { tags: {} } } }
{ metadata:
   { dynam: { tags: {} },
     bar: { post_title: {}, post_content_stripped: {}, tags: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {}, tags: {} } } }
{ metadata: { bar: { post_title: {}, post_content_stripped: {}, tags: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {}, tags: {} } } }
{ metadata: { dynam: { tags: {} }, bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { dynam: { tags: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { dynam: { tags: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }
{ metadata: { bar: { post_content_stripped: {} } } }

So a couple of issues
1.  It seems like the 'bar' match is taking into consideration the hyphenated tag.  This means that any tag in any of the blogs with a hyphen is returned.
2.  The hyphen seems to nullify the 'tag' field search.  I am guessing it is searching for 'dynamic' in tags and then after the hypen it searches every field?  Is this why I am receiving results from outside the 'tags' field?
3.  It is matching on 'dynam', which is fine in most cases.

I would like to have it do an exact search, whereas it only looks in the tags field for "dynamic-bars" with no stemming.  I have tried using ~0 in the search to disable a fuzzy search but that does not seem to solve the issue 2.

Also, instead of using a hyphen, what is the process to do an exact search on a several worded term? For instance
tag:dynamic bars  

I have tried this and it is obviously returning anything stemming from "dynamic" in the tags field and any other field that contains "bars".

Is there a way to tell lunr not to look for the stems of "dynamic" and "bars"?

Thank you!

**Comment by olivernn** [comment]
I think the cause of the issues you are seeing is what lunr considers a word separator. During indexing and query parsing lunr splits strings into tokens using [`lunr.tokenizer.separator`](https://github.com/olivernn/lunr.js/blob/master/lib/tokenizer.js#L57-L64). This considers spaces _and_ hyphens as word separators.

So when you have a document with a tags field with string value "animation callout dynamic-bars" lunr is turning that into the following tokens "animation", "callout", "dynamic" and "bars". You can see this by peeking at the data structure where all tokens are stored:

```javascript
'dynamic' in idx.invertedIndex //= true
'bars' in idx.invertedIndex //= true
'dynamic-bars' in idx.invertedIndex //= false
```

You have a couple of options to handle this case, the simplest is to use something other than a hyphen for joining multi word tags together. Alternatively you can change the value of `lunr.tokenizer.separator`.

If the tags field was an `Array` rather than a `String` then lunr would not attempt to split words at all, assuming that the string value of each element is already a token, e.g.

```javascript
tags = ["animation", "callout", "dynamic-bars"]
```

You'll still struggle to provide a search string to match this term though, the hyphen would still be considered a separator. You would be able to use the lower level `query` method though:

```javascript
idx.query(function (q) {
  q.term("dynamic-bars", { fields: ["tags"] })
})
```

The right solution depends on your data, the simplest approach is to modify `lunr.tokenizer.separator` so that it no longer considers a hyphen as a word separator, but you'd have to test with your data to ensure that doesn't cause any issues with any other documents/fields.

As for your other questions, lunr always does an exact match if there are no wildcards or edit distance specified. Stemming can be disabled during indexing by removing `lunr.stemmer` from the indexing and searching pipelines. To do a field based search for multiple terms prefix the term with the field names: `tags:dynamic tags:bars`.

I'm pretty sure that adjusting the way strings are split into tokens will solve your problem without having to change the stemming etc, let me know.

**Comment by chriskarkowsky** [comment]
Thank you!  I changed the data to make an array instead of a long string, and this works as i expect it to.

**Comment by nikolas** [comment]
To anyone else encountering this: I've solved this tag search issue by removing non-alphanumeric characters from tags: https://github.com/ccnmtl/digitaltibet/pull/57/files#diff-fa04d769d436c8b53acc38c2d9866efcR193
