### ISSUE TITLE
Searching for words prepended with underscores doesn't work

### ISSUE THREAD

**Issue by coliff** [olivernn/lunr.js#286]
My documents include many class names such `Msg_IDT_ZOOM`
- If I search for `Msg` I get results ✔️ 
- If I search for `Msg_IDT_` I get results ✔️ 
- If I search for `IDT` I get no results ❌ 
- If I search for `ZOOM` I get no results ❌ 

I'd like users to be able to search for `IDT` and `ZOOM` so that it shows `Msg_IDT_ZOOM` in the results - how can I do this?
I'm using Lunr.js through the mkdocs-material theme (http://squidfunk.github.io/mkdocs-material/)

**Comment by olivernn** [comment]
This is caused by what lunr considers to be a separator, by default an underscore is _not_ considered a separator.

This is easy to change, as described in this [fiddle](https://jsfiddle.net/a5L483aj/).

I'm not at all familiar with that mkdocs theme, so I'm not sure how you would make these changes in that context, perhaps open an issue on that project?

**Comment by coliff** [comment]
Thanks so much for taking the time to reply with the explaination and code example. I'm not really much of a JavaScript coder but I dug in to the JavaScript code for the MkDocs theme and replaced:
`tokenizer.separator=/[\s\-]` with `tokenizer.separator=/[\s\-\_]` and it worked! 👍

**Comment by olivernn** [comment]
Nice, glad its working for you!
