### ISSUE TITLE
Query / Tokenizing help, exact match

### ISSUE THREAD

**Issue by DominikTrenz** [olivernn/lunr.js#338]
Hey,

i can't find exact matches or combined fields using the query api.

A fiddle:
https://jsfiddle.net/wvpcdLaa/16/

Can you help me with that?

**Comment by hoelzro** [comment]
Hi @DominikTrenz!

From what I see, the reason this isn't working is because you're using the pipeline to index the documents, but _not_ using the pipeline for the search.  This means that you're looking for things like `M 225` in the inverted index, but only processed tokens like `m` and `225` exist in that index.

I don't know if lunr.js can handle exact searches across token boundaries - @olivernn do you have any thoughts on that?

**Comment by DominikTrenz** [comment]
But isn't
`
q.term(searchTerm, { boost: 100 }) // exact match
`
using the pipeline?
How can i use the pipeline? Removing 
` usePipeline: false`
on the other lines changes nothing.
The searching across token boundaries would be pretty important.

**Comment by hoelzro** [comment]
Yes, that first query _does_ use the pipeline - good point!  The issue here is that you're treating things like `M 225` as a singular token, but lunr.js doesn't index it as a single token.  Even if you disabled stemming, you would still have `m` and `225` as distinct tokens in your inverted index, causing your query never to match.

Let's back up a bit and talk about the higher level: what are you hoping to use lunr.js to do? Are you currently using lunr for search and hope to expand its use, or are you trying it out for a new search feature in an application?

**Comment by DominikTrenz** [comment]
I made a custom tokenizer for the room field. So the exact match problem should be gone. But i have no idea how to search across multiple fields

**Comment by olivernn** [comment]
I've updated the [fiddle](https://jsfiddle.net/wvpcdLaa/30/) and now get results for all three queries that I *think* make sense.

The problem you were seeing is that `lunr.Query#term` performs _no_ tokenisation of the term, i.e. uses that exact string in the search query. That means in the second query it is searching for the token "M 225". Unless you change the default tokeniser to _not_ split on white space this is _never_ going to match anything.

The `lunr.Query` interface could possibly make life a bit easier by accepting an array or a single object, and then calling `#toString()` on that object. That would allow you to do the following:

```javascript
q.term(lunr.tokenizer("foo bar baz"))
```

To be fair, the [current documentation](https://lunrjs.com/docs/lunr.Query.html#term) could make this a bit clearer also.

@DominikTrenz Does that solve your issue?

**Comment by olivernn** [comment]
2.2.0 includes the above mentioned change. I'm going to close this now as I _think_ we've covered everything, feel free to re-open or comment if not.
