### ISSUE TITLE
ref : "undefined" in result for search function

### ISSUE THREAD

**Issue by ganeshkbhat** [olivernn/lunr.js#345]
ref : "undefined" in search result for search. Here is my code and example array:

`mdArr = [{body:"# Getting started↵↵↵ Texting xxxx text", url:"/assets/mddocs/intro.md"}, {body:"Another body", url:"/assets/mddocs/intro.md"}]`

`searchString = 'text'`

```
function searchDocs(mdArr, searchString) {
  let result, docIndex = lunr(function () {
    this.field('url');
    this.field('body');
    for (var i = 0; i < mdArr.length; i++) {
      console.log('lunr', mdArr[i]);
      if (!!mdArr[i].body && (mdArr[i].body.indexOf('Error') !== 0 && !mdArr.err)) {
        let a = mdArr[i];
        this.add(a);
      }
    }
  });
  
  result = docIndex.search(searchString);
  console.log(result);
  return result;
}
```

![ref-undefined](https://user-images.githubusercontent.com/3424344/40270191-71c5233c-5ba6-11e8-842a-fe381a50bd86.png)

Any help is welcome? Missing something here?

**Comment by yeraydiazdiaz** [comment]
I believe the problem is that you have not specified a `ref` field, in that case Lunr attempts to retrieve an `id` field from your docs, but in your case there is none so `ref` is always `undefined`.

Seems you want to use the `url` field as a reference for the documents, I suggest simply changing `this.field('url')` for `this.ref('url')`, as described in [the "Getting started" guide](https://lunrjs.com/guides/getting_started.html).

**Comment by ganeshkbhat** [comment]
Thank you for your time. `this.ref('url')` worked and I was able to get the positions as well using `this.metadataWhitelist = ['position'];` . Kudos for the nice simple and flexible library. ;-)
