### ISSUE TITLE
Results aren't accurate for search

### ISSUE THREAD

**Issue by sosharma1403** [olivernn/lunr.js#364]
```
var lunr = require('lunr');
var documents = [{
  "name": "Lunr",
  "text": "this Like Solr, but much smaller, and not as bright."
}, {
  "name": "React",
  "text": "A JavaScript library for building user interfaces."
}, {
  "name": "Lodash",
  "text": "A modern JavaScript utility library delivering modularity, performance & extras."
}]

var idx = lunr(function () {
  this.ref('name')
  this.field('text')

  documents.forEach(function (doc) {
    this.add(doc)
  }, this)
})

console.log(idx.search("this"));

```

Should return match for `this`

**Comment by yeraydiazdiaz** [comment]
The reason Lunr returns no results for your query is because `this` is [one of the words filtered by the `stopWordFilter`](https://github.com/olivernn/lunr.js/blob/1476784e5f9923aae41dc9cca3b026361ef50586/lib/stop_word_filter.js#L139), which skips it during the indexing of the document as it's considered an non-content word in english.

Searching for other more meaningful words like `user` or `modular` does return results.

If you want full control over the index building process you skip using the `lunr` function and create a `lunr.Builder` manually removing the `stopWordsFilter` from the pipeline similar to [what the `lunr` function does](https://github.com/olivernn/lunr.js/blob/master/lib/lunr.js#L37).

**Comment by olivernn** [comment]
Just to add one thing, if you need a different set of words to be considered [stop words](https://en.wikipedia.org/wiki/Stop_words) you can use [`lunr.generateStopWordFilter`](https://github.com/olivernn/lunr.js/blob/1476784e5f9923aae41dc9cca3b026361ef50586/lib/stop_word_filter.js#L6-L19) to create a custom stop word filter. This is exactly how the [default stop word filter is created](https://github.com/olivernn/lunr.js/blob/1476784e5f9923aae41dc9cca3b026361ef50586/lib/stop_word_filter.js#L43).
