### ISSUE TITLE
Term presence mixed with fuzzy search on more than one keyword throws QueryParseError: Unexpected lexeme type 'PRESENCE'

### ISSUE THREAD

**Issue by mtdjr** [olivernn/lunr.js#369]
<img width="604" alt="screen shot 2018-08-14 at 10 08 10 pm" src="https://user-images.githubusercontent.com/8377553/44158139-0e3ef600-a082-11e8-9ff0-3aa73836b955.png">

**Comment by mtdjr** [comment]
Looks like if the fuzzy search comes last, there isn't an issue.
<img width="558" alt="screen shot 2018-08-15 at 12 35 40 pm" src="https://user-images.githubusercontent.com/8377553/44160219-c28f4b00-a087-11e8-80e6-a1196ab3eaf1.png">

**Comment by olivernn** [comment]
Thanks for taking the time to report this. It turns out the bug affected both terms with edit distance and terms with a boost. To trigger it required a term with either edit distance or boost, followed by a term with a presence.

I've put together a fix and cut a new release [2.3.2](https://www.npmjs.com/package/lunr/v/2.3.2).
