### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by nehalist** [olivernn/lunr.js#376]
I've recently played around with this library; and I'm a bit confused about the outcome for a certain example, see [this fiddle](https://jsfiddle.net/sgdofjw1/).

- "i", "im", "imp", "impre", "impres" returns 0 results
- "impress" returns 1 result
- "impressi" and "impressio" returns 0 results
- "impression" and "impressions" returns 1 result

Shouldn't every given input return 1 result? Am I missing something?

Edit: allowing wildcards results in getting 1 result until "impress" and 0 results for every letter afterwards.

**Comment by lucaong** [comment]
@nehalist, you are using the default settings, therefore exact match is performed, not prefix match nor fuzzy match. This explains why "i", "im", "imp", "impre", "impres" all return 0 results. If you search for "im*" (prefix search), you will get one result. Also, the default settings include stemming, so "impression" and "impressions" both get stemmed to "impress". That's why those three searches all return one result. You can turn off stemming if you want.

This is a modified version of your fiddle with stemming removed and prefix search: https://jsfiddle.net/sgdofjw1/1/

I hope this helps clarifying your doubts.

**Comment by nehalist** [comment]
Indeed, thanks a lot!
