### ISSUE TITLE
Results w/ same score sorting differently between IE and Chrome

### ISSUE THREAD

**Issue by davidcorrigan714** [olivernn/lunr.js#395]
I'm indexing and searching a long list of product names & versions. That tends to lead to results with an identical match score. I've noticed that on IE, results with the same match score are sorted one way, but in chrome the results are sorted the other way. I happen to prefer the way it's sorting in Chrome and I believe that matches the order I added the items to the index. The index is prebuilt and loaded from JSON, so that side of things is consistent between my tests. Either way, I'm curious what the cause might be.

**Comment by davidcorrigan714** [comment]
Sorting the results in my application was an improvement on both browsers so this doesn't matter to me anymore, but it might still be interesting to understanding how results with identical scores should be sorted.

**Comment by olivernn** [comment]
There isn't anything fancy going on with the [sort](https://github.com/olivernn/lunr.js/blob/56f571b11fc4c3e0b4f44c6e33889e3406e6d7f9/lib/index.js#L412), just using the plain old `Array#sort` provided by JavaScript. Because of this there is _every_ possibility that different JavaScript engines might implement this differently, the stable vs non-stable sort in your case.

I would imagine that sorting the results based on some application specific heuristic will provide the best results in these cases.
