### ISSUE TITLE
Considering union of results for multiple query tokens?

### ISSUE THREAD

**Issue by MihaiValentin** [olivernn/lunr.js#86]
At the moment when searching for multiple terms, only the documents containing _all_ the terms are included in the results. This is fine, however there are usecases when multiple keywords don't get many results (sometimes none at all) and it would be nice to add the documents that matched the individual terms on top of the intersected documents.

This could be configured as part of the `.search` method, by giving an additional argument to the search query.

`index.search('hello world', {union: true})`

Internally, this would do what it does now, but at the end also make an union between the individual terms and then add it at the end of the intersected results. Also, union'ed results could be marked using an additional property in order to know they are coming from the union so developers can present them in a different manner, if needed.

Is this something of interest for _lunr_? What do you think? If the answer is positive, I can come up with a PR proposal for this.

**Comment by httpdigest** [comment]
Maybe someone can help me with this, too, because I _think_ that my usecase is somewhat related to this.
So, what I would like to implement is a search with multiple search tokens returning only those documents that have all search tokens in either of the document fields. So, when I have documents with text fields `{a: "hello", b: "world"}`, and I am searching for `hello world` then that document should be returned.
What lunrjs and elasticlunr currently do by default, is to only return documents that match all search terms in a single document field.
I've tried the `bool` search option, but to no avail.

**Comment by olivernn** [comment]
This is an old issue, but Lunr 2.x does now support combining query terms with OR.
